### PR TITLE
Release 1.0.0 : Newswek Clone

### PR DESCRIPTION
**Pull request by mimipeshy**
Changelog

- Designed the three views, i.e mobile, tablet, and desktop screen sizes.

- Designed the navbar

- Placed rows in their respective order

- Designed the debate, opinion, news, editor, subscribe and footer section 

- Fixed HML validation errors

- Fixed stylelint errors

### CODE REVIEW

**Comment by peterrobert** [comment]
### PULL REQUEST UNDER REVIEW BY PETER ROBERT (TSE)

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED.
### GREAT PROJECT
**YOU HAVE DONE A GOOD JOB BUT THERE ARE SOME ISSUES THAT NEED TO BE ADDRESSED**

please fix the following issues.

- [ ] There should be margins in the left and right of your desktop view 
      yours 
margins
 original
margins original

- [ ] I noticed alot of responsiveness issues in your mobile view. KIndly take a step back and fix all the responsiveness issues before submitting it
responsiveness 763

- [ ] Your subscribe section doesnt look like the original
  yours 
subscribe

original
subscribe original

- [ ] Kindly fix your fonts. Most of them are big. KIndly make them look like the original clone.

- [ ] Another responsiveness issue. KIndly fix all the responsiveness issues
yours
responsiveness 763
original
resposiveness 763 orig

When you done fixing all the issues kindly submit your project again

**happy coding**

**Comment by sumancrest0001** [comment]
Status: Changes Required
Hello @mimipeshy,
You have done a great job to address the issues raised by the previous TSE. Most of them are resolved but it requires some minor changes to get approved. As you know this is a clone project, let's make it responsive as in the original page. Please make the following changes.
**Note: All the changes are mandatory.**
1. Sections like tech and science, sports, and culture are missing on a medium screen. It should be like this :point_down: 
Screenshot from 2020-06-14 13-46-00

### Changes required on a small screen

2. Subscribe section is different from the original one. Compare the differences :point_down: 
your project
Screenshot from 2020-06-14 13-46-54

original
Screenshot from 2020-06-14 13-47-09

3. Please make sure that aspect ratio of images are similar to the original one.
your project
Screenshot from 2020-06-14 13-49-00

4. Sign up form is repeating twice. remove one of them
Screenshot from 2020-06-14 13-48-31

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
Kindly make the requested changes and request another code review.
If you have any queries regarding the review, DM me on slack Suman Shrestha.

Happy coding !!!

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :recycle:  :stop_sign: 
Great work so far :clap:  You have Improved on the suggestions from the previous TSE :clap:  
However, there are a few more required changes :recycle:  Kindly improve on the following.

- [ ] The menu is losing responsiveness on the mobile view. Kindly Fix it 

yours :arrow_down: 
newsweek respo
Original :arrow_down: 
newsweek respo original

- [ ] When scrolling down the menu in the desktop view is moving off its container. Kindly fix that
 yours :arrow_down: 
menu_off_container

original :arrow_down: 
menu-off-container-original

- [ ] There is an error in your HTML :arrow_down: 
html error

### [OPTIONAL]
 On your mobile view, there is an overflow in the X-axis You can remove this by referencing the body tag and adding `overflow-x:hidden`.

I have noticed something wrong with your git-flow. It's okay to use both the master and development branches. But when you do make sure you make the development branch the default branch. Also, your pull request should be from the feature branch to the development branch

If you have any question about the review kindly contact me via slack on @peterrobert 

**HAPPY CODING**

**Comment by mimipeshy** [comment]
Thanks for the review. I will check on the git-flow and improve on it

**Review by HADDADSOHAIB — CHANGES_REQUESTED** [review]
### Status: Change Required :recycle: 

### Hello @mimipeshy   :hand: 

### Good job your project is getting better and better. :+1: 

### Unfortunately, there are still some changes to get the project approved:
- The issue raised by the previous review still not fixed:
Your project:
Screenshot from 2020-06-15 14-11-33
Orginal:
Screenshot from 2020-06-15 14-12-10
- The hamburger should not be in the desktop view:
Your project:
Screenshot from 2020-06-15 14-14-21
original:
Screenshot from 2020-06-15 14-15-12
- In very big resolution, your project should have a limit for the width: (at 4000px width)
original:
Screenshot from 2020-06-15 14-16-44
your project:
Screenshot from 2020-06-15 14-17-18
please fix that.

### Once you are done width the changes, please ask for another code review.

**Comment by mimipeshy** [comment]
I have done the changes. My project scales from mobile view to desktop view as per project guidelines. Be kind to me, I will check out how to further scale my project to fit all screen sizes, for now, I have no idea how it is done, none of my teammates know to how to limit the page either.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @mimipeshy, congratulations on fixing all the comments made by the previous TSE's :100: Thanks to their guidance and your persistence desire to learn and improve :+1: I hereby approve of your project :smile: Go ahead and merge to master, do not forget to submit the project completion form

_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by mimipeshy** [comment]
Thank you everybody!!!

**Pull request merged**
